language: haxe
sudo: required
haxe:
  - "3.4.4"
  - stable      # the latest stable release defined in https://haxe.org/download/list/
services:
  - mysql
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y curl imagemagick apache2 libapache2-mod-neko libmysqlclient-dev
  - sudo a2enmod neko
  - sudo a2enmod rewrite
  # For the following apache2 related operations, see https://docs.travis-ci.com/user/languages/php#Apache-%2B-PHP
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo cat /etc/apache2/sites-available/000-default.conf
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo cat /etc/apache2/sites-available/000-default.conf
  - sudo a2ensite 000-default.conf
  - sudo service apache2 restart
  - mysql -e 'CREATE DATABASE cagette;'
  - cp config.xml.dist config.xml
  - sed -e 's?database=.*?database="mysql://root:@localhost/cagette"?g' --in-place config.xml
  - sed -e 's?debug=.*?debug="1"?g' --in-place config.xml
  - sed -e 's?langs=.*?langs="fr;de;en"?g' --in-place config.xml
  - sed -e 's?langnames=.*?langnames="Français;Deutsch;English"?g' --in-place config.xml
install:
  - yes | haxelib install cagette.hxml
  - yes | haxelib install cagetteJs.hxml
before_script:
  - sudo sh -c "cd /usr/bin;haxelib run templo"
  - npm install
script:
  - haxe cagette.hxml
  - haxe cagetteJs.hxml
  - haxe templateGeneration.hxml
  - make -f Makefile_template templates LANG=fr
  - make -f Makefile_template templates LANG=de
  - make -f Makefile_template templates LANG=en
  - npm run build
  - index_page_output=$(wget http://cagette -O-)
  - wget_command_result=$?
  - if [ "$wget_command_result" != "0" ]; then echo "Error, could not access the web application." && exit 1; else echo "Successfully accessed the web application"; fi
  - if [ "$(echo \"$index_page_output\" | grep error | wc -l)" = "0" ]; then echo "First page access does not show an error, but it should" && exit 1; else echo "First page access shows an error, as expected"; fi
  - index_page_output=$(wget http://cagette -O-)
  - wget_command_result=$?
  - if [ "$wget_command_result" != "0" ]; then echo "Error, could not access the web application." && exit 1; else echo "Successfully accessed the web application"; fi
  - if [ "$(echo \"$index_page_output\" | grep error | wc -l)" != "0" ]; then echo "Second page access shows an error, but it should not" && exit 1; else echo "Second page access shows no error, as expected"; fi
  - haxe tests.hxml